### ISSUE TITLE
CSS / Layout Issue with Related Link box

### ISSUE THREAD

**Issue by juggs** [SoylentNews/rehash#184]
Example here: https://soylentnews.org/article.pl?sid=15/06/20/1850227

The comments are pushed way down the page to sit under the extended Related Links box (due to the number of links in the story).

Suggest floating the comments div to the left of the Related Links box (probably all boxes), so the comments are the same width as the story.

https://soylentnews.org/admin.pl?op=edit&sid=15/06/20/1850227 seems to manage to float content to the left of the boxes so we already have the required CSS in there.

There is a discussion to be had as to whether the Related Links box actually serves any useful purpose though :)

**Comment by paulej72** [comment]
The way the page is laid-out, we would have to do a major change to make the slashboxes flow correctly with the comments.  I would not want to restrict the comments only to the center column and not bot the center and right columns.  The real problem is the floats and css never seem to work like one thinks they should and you get some broken flows around stuff.

I think we should talk about removing the related links slashbox as it has been said that it is unnecessary in the past.  See #106.

**Comment by paulej72** [comment]
overflow-y: auto with a max-height of some value should fix it.

Fixed in #329
