### ISSUE TITLE
Need to check all input fileds to see if we need to encode quotes.

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/rehash#193]
Quoted text in poll question gets stripped
1.) Created a new poll on prod (https://soylentnews.org/) with this poll question:
'How often do you read a story's "from the something-something dept." line?'
2.) Clicked preview.
3.) Saw the quoted text and the surrounding double-quotes deleted. i.e., now had:
'How often do you read a story's line?'
4.) Tried again, but replaced each double-quote with &amp;quot; and clicked preview again.
5.) Saw each &amp;quot; replaced with a double quote. i.e., looked just like how I entered it in step 1.
6.) Clicked preview again.
7.) Saw the quoted text and the surrounding double-quotes deleted, i.e. just like I saw in step 3.

**Comment by paulej72** [comment]
Edit Poll user html input fields that use the value="ANSWER" format.  Any quotes in the Answer will end the value attribute so we need to use strip_subject on these fields rather than strip_title as strip_subject will encode quotes. This will be fixed as I create a pull that fixes all cases of this I can easily find.

**Comment by paulej72** [comment]
Fixed in Pull #195
