### ISSUE TITLE
No internationalization

### ISSUE THREAD

**Issue by vandenoever** [SoylentNews/rehash#280]
The rehash comment and moderation system is excellent. It would awesome to use it in different languages. There seems no way to run the site in any language other than English at the moment.

**Comment by TheMightyBuzzard** [comment]
Yeah, not likely to happen any time soon unless we get some volunteers who want to work on translating. The structure is mostly in place to do it all relatively easily but it's still going to be a mountain of work.

**Comment by vandenoever** [comment]
Could a volunteer translator step in or is coding know-how required?

**Comment by TheMightyBuzzard** [comment]
Absolutely. We'd welcome it. No coding required, just knowing where the strings of text are located. Most of them live in templates, though some will be stored in the database.

**Comment by TheMightyBuzzard** [comment]
The translator would need to learn to use git but that's easily learned well enough for our purposes.

**Comment by NCommander** [comment]
Late to this party, but I'd be willing to break out the strings into gettext templates if someone was serious on internationalizing the site. I brought it up a few times on SN, but the response to localizing has been negative to lukewarm because we're an English speaking site.

If you actually are planning on hosting a rehash instance, or an SN-spinoff, then we can talk about it.

**Comment by vandenoever** [comment]
I have no serious plans for hosting the site any more. The issue can be closed.

**Comment by burbilog** [comment]
@TheMightyBuzzard  @NCommander  How high is that mountain? :) 

Right now I'm considering rehash for a site (I read slashdot since '99, so I know what I'm looking for -- comments with meta-moderation) and I'd like to translate rehash to Russian language. So, how large is the problem? I can translate all strings, no problem, but I won't do internationalization coding, because my perl knowledge is really rusty and I have no knowledge of rehash internals. 

So... is it realistic to do it in reasonable amount of time?.. Is rehash ready for translation? Does it work with UTF8 (if I remember correctly, slashdot  does not)?

**Comment by NCommander** [comment]
It mostly depends if you want to load multiple interfaces at once. Most of
the strings are in the template files, and you can edit those relatively
freely, though a few strings are hardcoded in the source (not hard to
find). Loading UTF-8 encoded text should be relatively straight forward,
and *should* work as long as all the other components are good to go.

However, there hasn't been much headache aside from test code I wrote ages
ago in actually doing so. The response to i18n-ing SN was lackluster to say
the least, and I haven't had the energy or enough drive to do it anyway. It
should also be noted that while the Metamod code is present, and worked
(last I checked), the M2 values aren't connected to anything; the mod algo
takes no consideration into them when dolling out modpoints.
Michael

**Comment by burbilog** [comment]
> Most of the strings are in the template files, and you can edit those relatively freely, though a few strings are hardcoded in the source (not hard to find). 

Yes, I see that, but the question is how to organize templates so English does not intersect with Russian. There must be a set of default.en, default.ru, etc directories or some other way to maintain all languages at once in master branch. And thus it must be supported by rehash code. Otherwise it makes no sense to modify today copy of engine and forget about future updates. 

> The response to i18n-ing SN was lackluster to say the least, and I haven't had the energy or enough drive to do it anyway. 

It's a chicken and egg problem: you can't expect i18n support from native English speakers, while others walk in, look for internationalization and walk out without it... You can't have volunteers diving in without i18n being set up and ready for easy translation.

> It should also be noted that while the Metamod code is present, and worked (last I checked), the M2 values aren't connected to anything; the mod algo takes no consideration into them when dolling out modpoints.

Why it was dropped? SoylentNews seems to be low on traffic, so metamoderation is not a priority I guess, but considering large site this is the main reason to run slash/rehash...

**Comment by NCommander** [comment]
On Fri, Feb 24, 2017 at 10:53 AM, burbilog <notifications@github.com> wrote:

> Most of the strings are in the template files, and you can edit those
> relatively freely, though a few strings are hardcoded in the source (not
> hard to find).
>
> Yes, I see that, but the question is how to organize templates so English
> does not intersect with Russian. There must be a set of default.en,
> default.ru, etc directories or some other way to maintain all languages
> at once in master branch. And thus it must be supported by rehash code.
> Otherwise it makes no sense to modify today copy of engine and forget about
> future updates.
>

You can fork the templates into their own version. See soylentnews in the
themes folder, and the overlays that go ontop of it (chillax, etc), as such
you can layer over it.

The response to i18n-ing SN was lackluster to say the least, and I haven't
> had the energy or enough drive to do it anyway.
>
> It's a chicken and egg problem: you can't expect i18n support from native
> English speakers, while others walk in, look for internationalization and
> walk out without it... You can't have volunteers diving in without i18n
> being set up and ready for easy translation.
>

Yeah, I'm aware of that. We discussed hosting a localization version of the
site, like soylentnews.es or something like that but there was very little
interest, despite having a sizable European population. I'd be willing to
re-investigate i18n-ing the code, but its not going to be a small
undertaking.


> It should also be noted that while the Metamod code is present, and worked
> (last I checked), the M2 values aren't connected to anything; the mod algo
> takes no consideration into them when dolling out modpoints.
>
> Why it was dropped? SoylentNews seems to be low on traffic, so
> metamoderation is not a priority I guess, but considering large site this
> is the main reason to run slash/rehash...
>
> The original mod algro in slash is hilariously broken. It only works on
slashdot.org by luck and not because its correct, and will horridly skew
mod points to a few accounts and very irregularly at that. YOu won't get
working moderation with the original algorthimn unless you have
approximately 100k active users by rough back of the envelope math. When I
rewrote it the first time, M2 was broken, and right now, we just deal out
five mod points to anyone who isn't banned and there account is over a cut
off date.
